PRAGMA foreign_keys = ON;



CREATE TABLE IF NOT EXISTS IGP (

    ITMGRP TEXT PRIMARY KEY,
    ISACTIVE INTEGER

);

CREATE TABLE IF NOT EXISTS COLOR (
    COLOR TEXT PRIMARY KEY,
    CHEX TEXT,
    ISACTIVE INTEGER
);

CREATE TABLE IF NOT EXISTS GTL (

    GLSTEX TEXT PRIMARY KEY,
    ISACTIVE INTEGER

);

CREATE TABLE IF NOT EXISTS GSL (

    GLSOURCE TEXT PRIMARY KEY,
    SRCWEB INTEGER,
    GLSLOGO TEXT,
    GLSNOTE TEXT,
    ISACTIVE INTEGER

);

CREATE TABLE IF NOT EXISTS GTRNS (

    GTRNSN TEXT PRIMARY KEY,
    GTRNSV INTEGER
);

CREATE TABLE IF NOT EXISTS VENUE (

    VENUEID INTEGER PRIMARY KEY AUTOINCREMENT,
    VENUELOC TEXT,
    VMULTI INTEGER,
    VSDATE TEXT,
    VEDATE TEXT,
    VM INTEGER, VMST TEXT, VMET TEXT,
    VTE INTEGER, VTST TEXT, VTET TEXT,
    VW INTEGER, VWST TEXT, VWET TEXT,
    VR INTEGER, VRST TEXT, VRET TEXT,
    VF INTEGER, VFST TEXT, VFET TEXT,
    VST INTEGER, VSTST TEXT, VSTET TEXT,
    VSN INTEGER, VSNST TEXT, VSNET TEXT,
    ISACTIVE INTEGER

);

CREATE TABLE IF NOT EXISTS AUDIT (

    TRANSID INTEGER PRIMARY KEY AUTOINCREMENT,
    TRNOP TEXT CHECK(TRNOP IN ('INSERT', 'UPDATE', 'DELETE')),
    TRNOLD TEXT,
    TRNNEW TEXT,
    TRNCOL TEXT,
    TRNTBL TEXT,
    TRNTS TEXT DEFAULT CURRENT_TIMESTAMP

);

CREATE TABLE IF NOT EXISTS IVR (

    VARIID INTEGER PRIMARY KEY AUTOINCREMENT,
    ITMVARI TEXT,
    ITMGRP TEXT,
    ISACTIVE INTEGER,

    FOREIGN KEY (ITMGRP) REFERENCES IGP(ITMGRP) ON DELETE SET NULL ON UPDATE CASCADE

);

CREATE TABLE IF NOT EXISTS GSI (

    GLASSID INTEGER PRIMARY KEY AUTOINCREMENT,
    GLSNAME TEXT,
    GLSMANF TEXT,
    GLSLEN INTEGER,
    GLSWID INTEGER,
    GLSTHK INTEGER,
    GLSTEX TEXT,
    GLSIRI INTEGER,
    GLSOPAL INTEGER,
    GLSOURCE TEXT,
    GLLINK TEXT,
    GLSIMG TEXT,
    GLSNOTE TEXT,
    COLOR TEXT,
    GTRNSN TEXT,
    ISACTIVE INTEGER,

    FOREIGN KEY (GLSTEX) REFERENCES GTL(GLSTEX) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (COLOR) REFERENCES COLOR(COLOR) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (GLSOURCE) REFERENCES GSL(GLSOURCE) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (GTRNSN) REFERENCES GTRNS(GTRNSN) ON DELETE SET NULL ON UPDATE CASCADE

);

CREATE TABLE IF NOT EXISTS ITM (

    ITEMID INTEGER PRIMARY KEY AUTOINCREMENT,
    ITMNAME TEXT,
    ITMIMG TEXT,
    ONEOFF INTEGER,
    ITMGRP TEXT,
    VARINAME TEXT,
    CURRENT INTEGER,
    ITMPTRN TEXT,
    ITMSVG TEXT,
    ITMNOTE TEXT,
    ISACTIVE INTEGER,

    FOREIGN KEY (ITMGRP) REFERENCES IGP(ITMGRP) ON DELETE SET NULL ON UPDATE CASCADE,

);

CREATE TABLE IF NOT EXISTS IPC (
    ITEMID INTEGER,                           
    ITMPRICE NUMERIC,                         
    STDATE TEXT,                              
    ENDDATE TEXT,                             

    FOREIGN KEY (ITEMID) REFERENCES ITM(ITEMID) ON DELETE CASCADE ON UPDATE CASCADE

);

CREATE TABLE IF NOT EXISTS GPC (

    GLASSID INTEGER,                          
    GLSPRICE NUMERIC,                         
    STDATE TEXT,                              
    ENDDATE TEXT,                             

    FOREIGN KEY (GLASSID) REFERENCES GSI(GLASSID) ON DELETE CASCADE ON UPDATE CASCADE

);

CREATE TABLE IF NOT EXISTS IGC (

    COMPID INTEGER PRIMARY KEY AUTOINCREMENT,
    COMPNAME TEXT,
    ITEMID INTEGER,
    COMPNUM INTEGER,
    SVGREG INTEGER,
    GLASSID INTEGER,
    COMPLEN NUMERIC,
    COMPWID NUMERIC,
    COMPNOTE TEXT,
    ISSCRAP INTEGER,
    ISGRAIN INTEGER,
    ISACTIVE INTEGER,

    FOREIGN KEY (ITEMID) REFERENCES ITM(ITEMID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (GLASSID) REFERENCES GSI(GLASSID) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS ICC (

    ITEMID INTEGER PRIMARY KEY,
    IPCUT INTEGER DEFAULT 0,
    IPGRND INTEGER DEFAULT 0,
    IPFOIL INTEGER DEFAULT 0,
    IPSLDR INTEGER DEFAULT 0,
    IPDONE INTEGER DEFAULT 0,
    IPTS TEXT DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (ITEMID) REFERENCES ITM(ITEMID) ON DELETE CASCADE ON UPDATE CASCADE

);


CREATE TABLE IF NOT EXISTS ITR (

    ITRID INTEGER PRIMARY KEY AUTOINCREMENT,
    ITEMID INTEGER,
    IPCUT INTEGER DEFAULT 0,
    IPGRND INTEGER DEFAULT 0,                 
    IPFOIL INTEGER DEFAULT 0,                 
    IPSLDR INTEGER DEFAULT 0,                 
    IPDONE INTEGER DEFAULT 0,                 
    IPTS TEXT DEFAULT CURRENT_TIMESTAMP,      

    FOREIGN KEY (ITEMID) REFERENCES ITM(ITEMID) ON DELETE CASCADE ON UPDATE CASCADE

);

CREATE TABLE IF NOT EXISTS ITMSALE (

    SALEID INTEGER PRIMARY KEY AUTOINCREMENT, 
    ITEMID INTEGER,                           
    SUNITS INTEGER,                           
    SDATE TEXT,                               
    VENUEID INTEGER,                          

    FOREIGN KEY (ITEMID) REFERENCES ITM(ITEMID) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (VENUEID) REFERENCES VENUE(VENUEID) ON DELETE RESTRICT ON UPDATE CASCADE

);

CREATE TABLE IF NOT EXISTS TIMESALE (
    TSALEID INTEGER PRIMARY KEY AUTOINCREMENT, 
    TSTIME TEXT,                              
    TSUNITS INTEGER,                          
    TSDATE TEXT,                              
    VENUEID INTEGER,                          

    FOREIGN KEY (VENUEID) REFERENCES VENUE(VENUEID) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS GLSINV (
    GLSTRNID INTEGER PRIMARY KEY AUTOINCREMENT,
    GLASSID INTEGER,
    GLSSTOCK INTEGER,
    TS TEXT,

    FOREIGN KEY (GLASSID) REFERENCES GSI(GLASSID) ON DELETE SET NULL ON UPDATE CASCADE
);
