import sqlite3

# Define the database file name
DB_NAME = "inventory.db"



# Schema definition
SCHEMA = """
-- Enable Foreign Key Support
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS IGP (
    ITMGRP TEXT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS GTL (
    GLSTEX TEXT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS GSL (
    GLSOURCE TEXT PRIMARY KEY,
    SRCWEB INTEGER,
    GLSLOGO TEXT,
    GLSNOTE TEXT
);

CREATE TABLE IF NOT EXISTS VENUE (
    VENUEID INTEGER PRIMARY KEY AUTOINCREMENT,
    VENUELOC TEXT,
    VMULTI INTEGER,
    VSDATE TEXT,
    VEDATE TEXT,
    VM INTEGER,
    VMST TEXT,
    VMET TEXT,
    VTE INTEGER,
    VTST TEXT,
    VTET TEXT,
    VW INTEGER,
    VWST TEXT,
    VWET TEXT,
    VR INTEGER,
    VRST TEXT,
    VRET TEXT,
    VF INTEGER,
    VFST TEXT,
    VFET TEXT,
    VST INTEGER,
    VSTST TEXT,
    VSTET TEXT,
    VSN INTEGER,
    VSNST TEXT,
    VSNET TEXT
);

CREATE TABLE IF NOT EXISTS AUDIT (
    TRANSID INTEGER PRIMARY KEY AUTOINCREMENT,
    TRNOP TEXT CHECK(TRNOP IN ('INSERT', 'UPDATE', 'DELETE')),
    TRNOLD TEXT,
    TRNNEW TEXT,
    TRNCOL TEXT,
    TRNTBL TEXT,
    TRNTS TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS IVR (
    VARIID INTEGER PRIMARY KEY AUTOINCREMENT,
    ITMVARI TEXT,
    ITMGRP TEXT,
    FOREIGN KEY (ITMGRP) REFERENCES IGP(ITMGRP) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS GSI (
    GLASSID INTEGER PRIMARY KEY AUTOINCREMENT,
    GLSNAME TEXT,
    GLSMANF TEXT,
    GLSLEN INTEGER,
    GLSWID INTEGER,
    GLSTHK INTEGER,
    GLSTEX TEXT,
    GLSIRI INTEGER,
    GLSOPAL INTEGER,
    GLSOURCE TEXT,
    GLLINK TEXT,
    GLSIMG TEXT,
    GLSNOTE TEXT,
    FOREIGN KEY (GLSTEX) REFERENCES GTL(GLSTEX) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (GLSOURCE) REFERENCES GSL(GLSOURCE) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS ITM (
    ITEMID INTEGER PRIMARY KEY AUTOINCREMENT,
    ITMNAME TEXT,
    ITMIMG TEXT,
    ONEOFF INTEGER,
    VARIAT INTEGER,
    ITMGRP TEXT,
    VARIID INTEGER,
    CURRENT INTEGER,
    ITMPTRN TEXT,
    ITMNOTE TEXT,
    FOREIGN KEY (ITMGRP) REFERENCES IGP(ITMGRP) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (VARIID) REFERENCES IVR(VARIID) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS IPC (
    ITEMID INTEGER,
    ITMPRICE NUMERIC,
    STDATE TEXT,
    ENDDATE TEXT,
    FOREIGN KEY (ITEMID) REFERENCES ITM(ITEMID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS GPC (
    GLASSID INTEGER,
    GLSPRICE NUMERIC,
    STDATE TEXT,
    ENDDATE TEXT,
    FOREIGN KEY (GLASSID) REFERENCES GSI(GLASSID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS IGC (
    COMPID INTEGER,
    ITEMID INTEGER,
    COMPNUM INTEGER,
    GLASSID INTEGER,
    COMPLEN NUMERIC,
    COMPWID NUMERIC,
    COMPNOTE TEXT,
    PRIMARY KEY (COMPID, ITEMID),
    FOREIGN KEY (ITEMID) REFERENCES ITM(ITEMID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (GLASSID) REFERENCES GSI(GLASSID) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS ICC (
    ITEMID INTEGER PRIMARY KEY,
    IPCUT INTEGER DEFAULT 0,
    IPGRND INTEGER DEFAULT 0,
    IPFOIL INTEGER DEFAULT 0,
    IPSLDR INTEGER DEFAULT 0,
    IPDONE INTEGER DEFAULT 0,
    IPTS TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ITEMID) REFERENCES ITM(ITEMID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS ITR (
    ITRID INTEGER PRIMARY KEY AUTOINCREMENT,
    ITEMID INTEGER,
    IPCUT INTEGER DEFAULT 0,
    IPGRND INTEGER DEFAULT 0,
    IPFOIL INTEGER DEFAULT 0,
    IPSLDR INTEGER DEFAULT 0,
    IPDONE INTEGER DEFAULT 0,
    IPTS TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ITEMID) REFERENCES ITM(ITEMID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS ITMSALE (
    SALEID INTEGER PRIMARY KEY AUTOINCREMENT,
    ITEMID INTEGER,
    SUNITS INTEGER,
    SDATE TEXT,
    VENUEID INTEGER,
    FOREIGN KEY (ITEMID) REFERENCES ITM(ITEMID) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (VENUEID) REFERENCES VENUE(VENUEID) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS TIMESALE (
    TSALEID INTEGER PRIMARY KEY AUTOINCREMENT,
    TSTIME TEXT,
    TSUNITS INTEGER,
    TSDATE TEXT,
    VENUEID INTEGER,
    FOREIGN KEY (VENUEID) REFERENCES VENUE(VENUEID) ON DELETE RESTRICT ON UPDATE CASCADE
);
"""


def init_db():
    try:
        # Connect to SQLite database
        with sqlite3.connect(DB_NAME) as conn:
            cursor = conn.cursor()
            cursor.executescript(SCHEMA)
            cursor.execute("PRAGMA foreign_keys = ON;")

            print(f"Database successfully initialized at '{DB_NAME}'\n")

            # Verify tables
            cursor.execute(
                "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%';"
            )
            tables = cursor.fetchall()

            print("Created Tables:")
            for table in tables:
                print(f" - {table[0]}")

    except sqlite3.Error as e:
        print(f"An error occurred while initializing the database: {e}")


if __name__ == "__main__":
    init_db()
