PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS IGP (
    ITMGRP TEXT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS GTL (
    GLSTEX TEXT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS GSL (
    GLSOURCE TEXT PRIMARY KEY,
    SRCWEB INTEGER,
    GLSLOGO TEXT,
    GLSNOTE TEXT
);

CREATE TABLE IF NOT EXISTS VENUE (
    VENUEID INTEGER PRIMARY KEY AUTOINCREMENT,
    VENUELOC TEXT,
    VMULTI INTEGER,
    VSDATE TEXT,
    VEDATE TEXT,
    VM INTEGER, VMST TEXT, VMET TEXT,
    VTE INTEGER, VTST TEXT, VTET TEXT,
    VW INTEGER, VWST TEXT, VWET TEXT,
    VR INTEGER, VRST TEXT, VRET TEXT,
    VF INTEGER, VFST TEXT, VFET TEXT,
    VST INTEGER, VSTST TEXT, VSTET TEXT,
    VSN INTEGER, VSNST TEXT, VSNET TEXT
);

CREATE TABLE IF NOT EXISTS AUDIT (
    TRANSID INTEGER PRIMARY KEY AUTOINCREMENT,
    TRNOP TEXT CHECK(TRNOP IN ('INSERT', 'UPDATE', 'DELETE')),
    TRNOLD TEXT,
    TRNNEW TEXT,
    TRNCOL TEXT,
    TRNTBL TEXT,
    TRNTS TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS IVR (
    VARIID INTEGER PRIMARY KEY AUTOINCREMENT,
    ITMVARI TEXT,
    ITMGRP TEXT,
    FOREIGN KEY (ITMGRP) REFERENCES IGP(ITMGRP) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS GSI (
    GLASSID INTEGER PRIMARY KEY AUTOINCREMENT,
    GLSNAME TEXT,
    GLSMANF TEXT,
    GLSLEN INTEGER,
    GLSWID INTEGER,
    GLSTHK INTEGER,
    GLSTEX TEXT,
    GLSIRI INTEGER,
    GLSOPAL INTEGER,
    GLSOURCE TEXT,
    GLLINK TEXT,
    GLSIMG TEXT,
    GLSNOTE TEXT,
    FOREIGN KEY (GLSTEX) REFERENCES GTL(GLSTEX) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (GLSOURCE) REFERENCES GSL(GLSOURCE) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS ITM (
    ITEMID INTEGER PRIMARY KEY AUTOINCREMENT,
    ITMNAME TEXT,
    ITMIMG TEXT,
    ONEOFF INTEGER,
    VARIAT INTEGER,
    ITMGRP TEXT,
    VARIID INTEGER,
    CURRENT INTEGER,
    ITMPTRN TEXT,
    ITMNOTE TEXT,
    FOREIGN KEY (ITMGRP) REFERENCES IGP(ITMGRP) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (VARIID) REFERENCES IVR(VARIID) ON DELETE SET NULL ON UPDATE CASCADE
);
